src/Entity/Bulletin.php
<?php

namespace App\Entity;

use App\Repository\BulletinRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BulletinRepository::class)]
class Bulletin
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $category;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime')]
    private $creationDate;

    #[ORM\ManyToMany(targetEntity: 'App\Entity\Tag', inversedBy: 'bulletins')]
    #[ORM\JoinColumn(nullable: true)]
    private $tags;

    public function __construct(){
        $this->creationDate = new \DateTime("now");
        $this->tags = new ArrayCollection();
    }

    public function getColorCode(): string
    {
        //Cette méthode nous rend un code couleur CSS différent selon la catégorie de notre objet
        switch($this->category){ //Nous récupérons la valeur $category et la plaçons dans un switch
            case "Général":
                return "info";
            case "Divers":
                return "warning";
            case "Urgent":
                return "danger";
            default:
                return "secondary";
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }
}

templates/index/dataform.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ formName }} - {{ parent() }}{% endblock %}

{% block body %}
    <div style="max-width: 800px; margin: auto;">
        <h1>Formulaire {{ formName }}</h1>
        <div>
            {{ form(dataForm) }}
        </div>
    </div>
{% endblock %}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Bulletins - {{ parent() }}{% endblock %}

{% block body %}
    <div style="max-width: 800px; margin: auto;">
      <h1 class="display-2">Liste des Bulletins</h1>
      <a href="{{ path('bulletin_generate') }}" type="button" class="btn btn-danger">Générer Bulletin</a>
      <a href="{{ path('bulletin_create') }}" type="button" class="btn btn-success">Créer Bulletin</a>
      <a href="{{ path('tag_create') }}" type="button" class="btn btn-primary">Créer Tag</a>

      {% for bulletin in bulletins %}
        <div class="alert alert-{{ bulletin.colorCode }}" style="margin-top:20px">
            <h3 class="display-5">{{ bulletin.title }}</h3>
            <p class="h2">{{ bulletin.category }}</p>
            <p>{{ bulletin.content|nl2br }}</p>
            <p class="lead">Date de création: {{ bulletin.creationDate|date('d/m/Y à G:i:s', 'Europe/Paris') }}</p>
            <p>
              <b>Tags:</b>
              {% if bulletin.tags is not empty %}
                {% for tag in bulletin.tags %}
                  <a href="{{ path('index_tag', {'tagId' : tag.id}) }}">{{ tag.name }}</a>;
                {% endfor %}
              {% else %}
                <i>Aucun.</i>
              {% endif %}
            </p>
            <a href="{{ path('bulletin_display', {'bulletinId' : bulletin.id}) }}" type="button" class="btn btn-primary">Afficher</a>
            <a href="{{ path('bulletin_update', {'bulletinId' : bulletin.id}) }}" type="button" class="btn btn-warning">Modifier</a>
            <a href="{{ path('bulletin_delete', {'bulletinId' : bulletin.id}) }}" type="button" class="btn btn-danger">Supprimer</a>
        </div>
      {% endfor %}

    </div>
{% endblock %}

templates/index/taglist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Tags - {{ parent() }}{% endblock %}

{% block body %}
    <div style="max-width: 800px; margin: auto;">
      <h1 class="display-2">Liste des Tags</h1>
      <a href="{{ path('tag_create') }}" type="button" class="btn btn-primary">Créer Tag</a>

      <ul class="list-group list-group-flush" style="margin-top:20px;">
        {% for tag in tags %}
            <li class="list-group-item">
                <p>
                    {{ tag.name }}
                    <a href="{{ path('tag_delete', {'tagId' : tag.id}) }}" type="button" class="btn btn-danger" style="float:right">Supprimer</a>
                </p>
            </li>
        {% endfor %}
      </ul>      

    </div>
{% endblock %}